### ISSUE TITLE
Distinguish between fatal() and critical() in adapter

### ISSUE THREAD

**Issue by nrdvana** [dagolden/Log-Any#20] opened 2015-01-20 07:59 UTC
One adapter I wrote (Log::Any::Adapter::TAP) writes the method name in the output.  Now that Log::Any::Proxy is normalizing calls, all the ->fatal() show up as "critical: ".

I'm fine with these having the same numeric level, but it really seems like the back-end adapter ought to be told which method was called.  There could be other logging packages that care about this difference, and Log::Any's selection of method names was to "be inclusive of all the major logging packages".

Looking at the code, I can't see any way around the problem that doesn't blatantly violate the new API.

**Comment by dagolden** [comment] 2015-01-20 16:05
I think that might be feasible.  Log::Any::Adapter::Base needs to redispatch aliases to the primary method name.  Adapters that care about the method invoked can implement the alias method themselves.

**Comment by xdg** [comment] 2016-02-02 22:26
On reflection, I think the normalization is a feature, not a bug.  Loggers should care about the levels invoked, not which synonym is used.  I'm going to close this "won't fix".

**Closed by xdg** 2016-02-02 22:26 UTC
