### ISSUE TITLE
Wishlist: allow adapters to override stringification of refs

### ISSUE THREAD

**Issue by nrdvana** [dagolden/Log-Any#21] opened 2015-01-20 08:10 UTC
While producers generally know what data they are writing, and can choose an appropriate dumper for it, sometimes adapters want to handle the objects directly.  For instance, a consumer might serialize the object to a database, or directory, or etc, while returning a small placeholder string indicating where the data can be found.  It would be nice if the default proxy could check with the consumer to find out if the consumer has a preferred dumper.

**Comment by dagolden** [comment] 2015-01-20 16:13
I think that's not consistent with the division between log production and log consumption.  The original design was very clear that strings were the lowest-common denominator.

I could imagine extending the API to allow adapters to provide an "object stringification callback", but nothing would stop producers from defining their own message formatting function that ignores it, which mean that sometimes objects would get dumped the way adapters want and sometimes they aren't, which seems like it defeats the goal.

I'll leave this open as a wishlist item, but I can't think of a good way to make it work the way you want.

**Comment by silverdirk** [comment] 2015-01-21 00:47
I think the more general wishlist item is that a consumer might want to override handling of some aspect of the Log::Any::Proxy being used, but also cooperate with the Log::Any::Proxy that the producer chose. (the formatting function and so on)

So for example,
  * in this issue I'd like to capture objects before they get stringified
  * in some programs I'd like the option to trap exceptions thrown during debug() or trace()
  * in some programs I'd like to short-circuit disabled log levels so that stringification doesn't happen

You have the OverrideDefaultProxy mechanism, but this completely disables any choices the producer made.  Also it must be decided before the producer module is loaded.

If we tell the adapter about each instance of a Proxy, then the adapter could dynamically create a subclass of the proxy (and re-bless it) in order to wrap its methods.  This would give the adapter those abilities above and also handle some of the other wishlist items.

I wrote up the start of the idea here:
https://github.com/silverdirk/Log-Any/commit/87a89204cc3fa2f3b69a8a29744676e2ec653452

In fact, that is enough as-is, but I think it would be good to also provide some utility functions to aid the adapter in subclassing the proxy.  I'm still thinking about how those would look.

**Comment by silverdirk** [comment] 2015-01-21 20:36
oh, and I meant to end that with "How do you feel about the direction of that patch?  Should I continue working on this?"

**Comment by dagolden** [comment] 2015-01-21 21:06
I've only had time to look at it briefly.  I'm concerned about the added complexity.  However, I'm already considering tracking proxies to rebless them when the adapter is the Null adapter, so some of what you propose is consistent with that.

Where I'm hung up is what is considering going to violate expectations of users of the proxy and lead to unexpected behavior.  Along those lines, I'm pondering whether reblessing is a good general mechanism or if specific hooks ought to be made available for adapters instead.

To your specific examples:

* capturing objects → Short of just capturing raw arguments to "*f" etc methods, I'm not sure this can be done robustly.  You can't replace the object with some placeholder string/object because the formatting function might actually be expecting an object of a particular type (e.g. an exception object).  I can imagine some sort of "raw mode" where formatting is skipped and the raw arguments are passed to some other adapter method, and then it's up to the consumer to do useful things for that application.

* trapping exceptions → what sort of exceptions did you mean?  Like if the logging itself fails?  I don't see why that needs to be on the proxy.  I would think that would just get trapped within the adapter itself.

* short-cut disabled log functions → this already happens for the *f functions

**Comment by dagolden** [comment] 2015-01-21 21:06
To clarify, I'm not saying "no", but I'm not saying "yes", either.  There's a lot to ponder here.

**Comment by silverdirk** [comment] 2015-01-26 19:24
I've been thinking on it more, and you're right about the "strings are the lowest common denominator".  The things I've been trying to do with object-passing break the official API even of the old Log::Any version.

My motivation for that idea, though, is to get the effects of the Javascript console.log().  That is a beautiful logging API because it lets the browser capture whole objects, and then you can navigate into them from the developer tools of the browser.

I have a new idea to approach this though.  I could make a new Proxy class that exposes a different API to the producer with the semantics of the javascript logger.  Only modules who want this API would ask for this class, so there's no breakage for anyone else.  The Proxy would then check the adapter to see if the adapter supported a special method to receive these objects.  If not, the Proxy would convert the objects to strings and use the normal logging methods.  And best of all, this could be done without altering the core Log::Any at all.

If you like that idea though, I'd like to include a mention of the optional API in the documentation for Adapter authors.

**Comment by silverdirk** [comment] 2015-01-26 21:49
On the topic of hooks vs subclasses, it can be hard to anticipate all the things people might want hooked.  Also hooks add up as performance penalties over time.  The idea that I think I like best is Moose/Moo's role composition, to produce a class composed of various functionality rolled into one.

Of cource I don't want Moose/Moo dependencies added to Log::Any, but multiple inheritance can accomplish almost as much as roles, and its quite easy to produce a new class on the fly which inherits from a list of other classes.  (just define the @ISA variable for it, and done.)  It's also the most efficient outcome, because only the functionality being used is paid for.

**Comment by dagolden** [comment] 2015-01-26 23:34
On Mon, Jan 26, 2015 at 2:24 PM, silverdirk <notifications@github.com>
wrote:

> I have a new idea to approach this though. I could make a new Proxy class
> that exposes a different API to the producer with the semantics of the
> javascript logger. Only modules who want this API would ask for this class,
> so there's no breakage for anyone else. The Proxy would then check the
> adapter to see if the adapter supported a special method to receive these
> objects. If not, the Proxy would convert the objects to strings and use the
> normal logging methods. And best of all, this could be done without
> altering the core Log::Any at all.


My quick take is positive.  I think it's a good example of the goal of
Proxy -- to allow producers to do things independent of the consumer
capabilities.

**Comment by xdg** [comment] 2016-02-02 16:54
I'm doing ticket triage and given that the proposed solution is outside Log::Any, I'm going to close this ticket.

**Closed by xdg** 2016-02-02 16:54 UTC

**Comment by nrdvana** [comment] 2016-02-02 19:27
The optional API should still be documented in the adapter API so that authors agree on how it's done, and it might make sense to make some available in the "use Log::Any ..." syntax.  If they are small it would also make sense to add them to the Log::Any dist.

i.e.
```
# This is the API I want, for passing refs to the back end to be rendered.
# Each method would also return the data, giving the pass-through feature
# that lots of people want.
use Log::Any '$log', api => 'LogData';

# This is the lazy-eval-the-coderefs API that lots of people want
use Log::Any '$log', api => 'EvalSubs';
```

I would propose some complete ideas if you had time to review them.  Or, I could just write independent packages with Proxy classes in the Log::Any namespace if you don't mind.

**Comment by xdg** [comment] 2016-02-02 19:45
I think writing separate packages is the way to go.
