### ISSUE TITLE
memory leak if adapter is repeatedly added to the adapter stack

### ISSUE THREAD

**Issue by dagolden** [dagolden/Log-Any#25] opened 2015-02-28 21:35 UTC
Reported by @rehsack via email:

In a recent project, which is reusing the class provided by https://github.com/rehsack/System-Image-Update/blob/master/lib/System/Image/Update.pm in a web-service which re-instantiates the class on each request regarding to the update status, the leak is caused by https://github.com/rehsack/System-Image-Update/blob/master/lib/System/Image/Update/Role/Logging.pm - according to the documentation of Log::Any (https://metacpan.org/pod/Log::Any::Adapter).

Every time the web-service is proving the system image update status, attached leak
 occurs (because of accidentally repeated Log::Any::Adapter initialization in the appropriate role).

Leak log:
```
leaked SCALAR(0xa0b300) from /usr/lib/perl/vendor_perl/5.14.3//JSON/backportPP.pm line 909.
leaked SCALAR(0xbd4978) from /usr/lib/perl/vendor_perl/5.14.3//Log/Any/Manager.pm line 80.
leaked REGEXP(0xbd3cc8) from /usr/lib/perl/vendor_perl/5.14.3//Module/Pluggable/Object.pm line 301.
leaked SCALAR(0x10d4c00) from /usr/lib/perl/vendor_perl/5.14.3//JSON/backportPP.pm line 909.
leaked SCALAR(0x1148948) from /usr/lib/perl/vendor_perl/5.14.3//JSON/backportPP.pm line 909.
leaked ARRAY(0x115bf78) from /usr/lib/perl/vendor_perl/5.14.3//Log/Any/Manager.pm line 80.
leaked REF(0x1177c38) from /usr/lib/perl/vendor_perl/5.14.3//Log/Any/Manager.pm line 121.
leaked SCALAR(0x11778d8) from /usr/lib/perl/vendor_perl/5.14.3//Log/Any/Manager.pm line 181.
leaked SCALAR(0x1177858) from /usr/lib/perl/vendor_perl/5.14.3//Config/Any/JSON.pm line 71.
leaked SCALAR(0x116d8b8) from /usr/lib/perl/vendor_perl/5.14.3//Class/Load/PP.pm line 34.
leaked GLOB(0x11c2510) from /usr/lib/perl/vendor_perl/5.14.3//Log/Any/Manager.pm line 181.
leaked SCALAR(0x11c24e0) from /usr/lib/perl/vendor_perl/5.14.3//Log/Any/Manager.pm line 121.
leaked HASH(0x11c24a0) from /usr/lib/perl/vendor_perl/5.14.3//Log/Any/Manager.pm line 121.
leaked REF(0x11c2380) from /usr/lib/perl/vendor_perl/5.14.3//Log/Any/Manager.pm line 97.
leaked SCALAR(0x11cb560) from /usr/lib/perl/vendor_perl/5.14.3//JSON/backportPP.pm line 909.
leaked REF(0x11c8620) from /usr/lib/perl/vendor_perl/5.14.3//Log/Any/Manager.pm line 80.
leaked REGEXP(0x11c8530) from /usr/lib/perl/vendor_perl/5.14.3//Module/Pluggable/Object.pm line 314.
leaked REGEXP(0x11c8520) from /usr/lib/perl/5.14.3//File/Find.pm line 968.
leaked ARRAY(0x11c8510) from /usr/lib/perl/vendor_perl/5.14.3//JSON/backportPP.pm line 894.
leaked SCALAR(0x11c8450) from /usr/lib/perl/vendor_perl/5.14.3//JSON/backportPP.pm line 909.
leaked SCALAR(0x11c8440) from /usr/lib/perl/vendor_perl/5.14.3//JSON/backportPP.pm line 909.
leaked SCALAR(0x11c83d0) from /usr/lib/perl/vendor_perl/5.14.3//JSON/backportPP.pm line 909.
leaked SCALAR(0x11c83c0) from /usr/lib/perl/vendor_perl/5.14.3//JSON/backportPP.pm line 909.
leaked REF(0x11c83a0) from /usr/lib/perl/vendor_perl/5.14.3//JSON/backportPP.pm line 909.
leaked ARRAY(0x11c8350) from /usr/lib/perl/vendor_perl/5.14.3//JSON/backportPP.pm line 894.
leaked SCALAR(0x11c8340) from /usr/lib/perl/vendor_perl/5.14.3//JSON/backportPP.pm line 909.
leaked REGEXP(0x11c8300) from /usr/lib/perl/vendor_perl/5.14.3//Text/Glob.pm line 18.
leaked ARRAY(0x11c82d0) from /usr/lib/perl/vendor_perl/5.14.3//JSON/backportPP.pm line 894.
leaked SCALAR(0x11c82c0) from /usr/lib/perl/vendor_perl/5.14.3//JSON/backportPP.pm line 909.
leaked REGEXP(0x11c82b0) from /usr/lib/perl/vendor_perl/5.14.3//Log/Any/Manager.pm line 87.
leaked SCALAR(0x11c82a0) from /usr/lib/perl/vendor_perl/5.14.3//JSON/backportPP.pm line 909.
leaked REF(0x11c8290) from /usr/lib/perl/vendor_perl/5.14.3//JSON/backportPP.pm line 909.
leaked SCALAR(0x11c8250) from /usr/lib/perl/vendor_perl/5.14.3//JSON/backportPP.pm line 909.
leaked GLOB(0x11c8200) from /usr/lib/perl/vendor_perl/5.14.3//Log/Any/Manager.pm line 181.
leaked SCALAR(0x11c81e0) from /usr/lib/perl/vendor_perl/5.14.3//System/Image/Update/Role/Logging.pm line 30.
leaked REF(0x11c81d0) from /usr/lib/perl/vendor_perl/5.14.3//Log/Any/Manager.pm line 121.
leaked REGEXP(0x139eff0) from /usr/lib/perl/5.14.3//File/Find.pm line 763.
leaked SCALAR(0x139ef00) from /usr/lib/perl/vendor_perl/5.14.3//JSON/backportPP.pm line 909.
 ```

**Comment by dagolden** [comment] 2015-02-28 21:47
@rehsack, do you know what version of Log::Any was in use?  I don't see anything around those line numbers that would seem to leak.

**Comment by rehsack** [comment] 2015-02-28 22:01
Sure, it was/is 1.03 - and is still: https://github.com/rehsack/meta-cpan/tree/master/recipes-devel/log-any-perl

The reason of the leak is, that Log::Any::Adapter->set(..) only pushes. I don't know since when it returns an entry object for ->remove (I've seen it today first time - which means I blamed maybe the wrong module ^^).

However - I detected an issue there which is caused by using MooX::Log::Any according to the docs and maybe the usage in MooX::Role::Logger is better but I have no clue about gluing config files and MooX::Role::Logger ...

**Comment by dagolden** [comment] 2015-02-28 22:08
Interesting.  That might be a design flaw, since the idea is that adapters are in a priority stack.

Possibly, if the adapter is not being set as a lexical adapter (which gets popped when the guard object is destroyed), then the adapter should not be added if it is already on the top of the stack.

Thanks for the report.  I'm not sure when I'll find the tuits for this, but I'm glad to have a diagnosis at least.

**Comment by rehsack** [comment] 2015-02-28 22:09
See #toolchain - I think having a ->new() which automatically calls ->remove on destruction could help out easily

**Comment by xdg** [comment] 2016-02-03 15:14
Seems like this can be fixed by having a DEMOLISH method:

```perl
sub DEMOLISH {
    my $self = shift;
    Log::Any::Adapter->remove($self->log_adapter) if $self->has_log_adapter;
}
```

**Comment by rehsack** [comment] 2016-02-03 16:10
Unfortunately that's a similar workaround as https://github.com/dagolden/Log-Any/issues/25#issuecomment-76550048 - and hides the design flaw behind a responsibility discussion.

It's kind-of nasty that Log::Any::Adapter->set(...) is implemented similar to malloc/free ...

I have no idea how to fix that in a API stable and perlish way ... but documenting it and mind the workarounds is a starter ...

**Comment by xdg** [comment] 2016-02-03 16:26
I believe the original design of Log::Any::Adapter assumed that it would only be set once.  Oh, well.

I think the lexical approach would work too, though that is the same thing as DEMOLISH, really.

If you really want horror, look at https://github.com/dagolden/Log-Any/blob/master/lib/Log/Any/Manager.pm#L141-L142

A design that relies on replacing the guts of a reference and reblessing it has got to be on my top-10 list of Perl abuses.

**Comment by rehsack** [comment] 2016-02-03 16:52
:+1: 
So what remains is public documentation - maybe additionally in https://metacpan.org/pod/MooX::Log::Any, too @cazador481

**Comment by xdg** [comment] 2016-02-03 17:10
It is documented in Log::Any::Adapter (set, remove, the stack, etc.).  What do you think is missing?  Or rather what would have helped you avoid the leak?

**Comment by rehsack** [comment] 2016-02-03 17:47
I do not see any line in Log::Any::Adapter which tells that the stack must be manually cleaned up. It is simply unexpected that one must care the resource management on his own.

https://github.com/dagolden/Log-Any/blob/master/lib/Log/Any/Adapter.pm#L185-L191 contains the information - but the leak doesn't come from multiple adapter setting, it was the same again and again because of code-reuse between a CLI- (used once) and a Web-App (used dozens, accidently).

What would helped? A dedicated section wrt. Resource Management.

=head1 RESOURCE MANAGEMENT

C<Log::Any> maintains a stack of entries created via C<set>.

Each entry added must either be removed manually (list handle example, DEMOLISH, ...) or will be freed at end of program when global destruction destroys Log::Any::Manager instance.

**Comment by xdg** [comment] 2016-02-03 18:02
Please take a look at this diff and tell me if you think it covers what needs to be said: https://gist.github.com/xdg/77d0b9992d8283bd1d66

**Comment by rehsack** [comment] 2016-02-03 18:17
It's not as expressive as I would like it, but it does the job :+1:

**Comment by xdg** [comment] 2016-02-03 18:32
Done in 47d1e7f1e542dc08a1a374275eed7b22a7145678

**Closed by xdg** 2016-02-03 18:32 UTC
Labels: investigating

**Comment by cazador481** [comment] 2016-02-03 19:53
So if I understand correct the comments about, I should have MooX::Log::Any should add a DEMOLISH subroutine that will clean the logger that it created.  Did I understand correctly?

**Comment by rehsack** [comment] 2016-02-03 20:04
@cazador481 - better an example with the DEMOLISH subroutine together with the log_adapter attribute ... I can send you a patch, if you want.

**Comment by cazador481** [comment] 2016-02-03 20:12
@rehsack Thanks I would appreciate the patch.
